spring:
   application:
        name: Kafka-springboot
kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      retries: 3
      batch-size: 16384 
      linger-ms: 5 
      buffer-memory: 33554432 
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      properties:
        spring.json.trusted.packages: "*"
